### ISSUE TITLE
How to start criu service

### ISSUE THREAD

**Issue by 123toorc** [checkpoint-restore/criu#1000]
I want to do live migration, it's mentioned that I need to use CRIU RPC, after I make install criu, I did $systemctl start criu. It looks like criu.service or criu.socket didn't register in systemd, what steps I missed?

**Comment by Snorch** [comment]
I don't think it is supported:

```commit 10d5e9a43e4350ac9f1b607e1b261ab56444c1bb
Author: Ruslan Kuprieiev <rkuprieiev@cloudlinux.com>
Date:   Mon Oct 12 12:50:01 2015 +0300

    criu: scripts: remove criu service files
    
    As it is not recomended to run criu as a root system service, lets
    remove service file to stop encouraging people to do it.
    
    Signed-off-by: Ruslan Kuprieiev <rkuprieiev@cloudlinux.com>
    Signed-off-by: Pavel Emelyanov <xemul@parallels.com>
```
May be @efiop and @xemul can say more.

@avagin I can remove this info from wiki if you give a green light. https://criu.org/RPC#systemd

**Comment by adrianreber** [comment]
Also see: https://lists.openvz.org/pipermail/criu/2015-August/021847.html

**Comment by xemul** [comment]
The service is no longer supported, if you want love migration run criu dump and restore as usually -- via fork+exec

**Comment by Snorch** [comment]
>The service is no longer supported, if you want live migration run criu dump and restore as usually -- via fork+exec
=> removed systemd service info from wiki

**Comment by 123toorc** [comment]
Thank you! So live migration already integrated inside CRIU? what extra steps need to do except dump, copy images, and restore?

**Comment by adrianreber** [comment]
> what extra steps need to do except dump, copy images, and restore?

Nothing. That is already everything that is necessary.

**Comment by 123toorc** [comment]
But what is the difference operation between normal migration and live migration? I am super confused.

**Comment by adrianreber** [comment]
> But what is the difference operation between normal migration and live migration? I am super confused.

That is just a definition. I guess. Either you can say it is a live migration because you are using CRIU to migrate the process with its complete state. So not shutdown and restart. Maybe stateful migration = live migration.

Or you could define a live migration by the downtime. There will always be a downtime, for a live migration you want to make the downtime as small as possible. So you can use one of the features of CRIU to reduce the downtime: pre-copy and post-copy; that would be a bit more complicated than dump, copy images, and restore. In the end, however, it will always be dump, copy images, and restore just with clever additional steps in between.

I would say live migration is just what you define as live migration.

What do you expect when you write 'live migration'?

**Comment by 123toorc** [comment]
Thank you so much! My understanding is that with checkpoint restart I stop the application, move all the image files, and then restart the application, with live migration instead, I move the image files while the application is still running. So in summary, just do more pre-dump and pre-copy and reduce the downtime as much as possible before the real dump is a live migration right?

**Comment by adrianreber** [comment]
> So in summary, just do more pre-dump and pre-copy and reduce the downtime as much as possible before the real dump is a live migration right?

Yes. It seems your definition of live migration is to reduce downtime.

I wrote an article a few years ago about runc and reduced downtime: https://www.redhat.com/en/blog/container-migration-around-world

In the article there are links to a few scripts to use runc in combination with pre-copy and post-copy. Maybe that would be interesting for you.

Closing this now, as CRIU does not support the service feature anymore.
