### ISSUE TITLE
CRIU commercial support

### ISSUE THREAD

**Issue by anujkumar-df** [checkpoint-restore/criu#1017]
Is there something like commercial support available? We want to c/r process other than containers, such as java, MySQL, httpd, etc.

**Comment by Snorch** [comment]
My opinion is that migration _with_ "container" is much easier because the container implicitly removes a lot of external dependencies (for which criu needs user assistance by design). Without the "container" you need to manually investigate each external dependency for each application and it can be a pain. That's why we are concentrating on "container"s mostly...

In Virtuozzo container (system container) you can run any application inside and if it's resources are supported it would migrate. Maybe it is what you want... =)

**Comment by anujkumar-df** [comment]
I understand container provides a much narrow view of the process than a process running on a VM. The question is not about simplicity. We have a limited number of applications and we believe that after a few iterations, we can c/r them. We are not looking for criu as a silver bullet :)

**Comment by anujkumar-df** [comment]
Just to simplify, what we are looking for is the correct usage of criu parameters, so we know the implications of c/ring processes. We are not looking for any new feature development (if it doesn't already exist).

**Comment by adrianreber** [comment]
Just ask here. If the features already exist it should be no problem to answer your questions.

**Comment by anujkumar-df** [comment]
We have a time constraint, so we need premium support. But if that doesn't exist in CRIU, that's fine. Please let me know and I will close the issue.

**Comment by adrianreber** [comment]
I am not aware of any commercial support. I would still recommend asking your questions here maybe we can help you.

**Comment by anujkumar-df** [comment]
Thanks, I will.
