### ISSUE TITLE
Can CRIU support restore old snapshot after system upgraded?

### ISSUE THREAD

**Issue by geminijun** [checkpoint-restore/criu#1049]
I tried it, and seems the restore will be failed, when CRIU found the size of shared library has been changed.

I have a question, the shared library is fully loaded in the memory already, correct? Is that possible to save that memory, and when restore just restore the old states? For those shared libraries, we don't need to load them anymore, correct?

**Comment by adrianreber** [comment]
If a library changes between checkpoint and restore the restored process will still jump to the old addresses of the library functions. That is why the size check exist, it is not perfect as a library could change and by chance still have exactly the same size as before, but that is unlikely. I think there was a GSoC project discussed to do this better.

> I have a question, the shared library is fully loaded in the memory already, correct? Is that possible to save that memory, and when restore just restore the old states? For those shared libraries, we don't need to load them anymore, correct?

If you link your binary statically you can easily achieve this.

**Comment by geminijun** [comment]
> If a library changes between checkpoint and restore the restored process will still jump to the old addresses of the library functions. That is why the size check exist, it is not perfect as a library could change and by chance still have exactly the same size as before, but that is unlikely. I think there was a GSoC project discussed to do this better.
> 
> > I have a question, the shared library is fully loaded in the memory already, correct? Is that possible to save that memory, and when restore just restore the old states? For those shared libraries, we don't need to load them anymore, correct?
> 
> If you link your binary statically you can easily achieve this.

Even for the shared libraries, will it cause problem just let the process jump to the old addresses of the library functions? I think the shared libraries are loaded into memory already, it won't reload the new one on filesystem unless process using ```dlopen```, correct?

**Comment by avagin** [comment]
>  I think the shared libraries are loaded into memory already, it won't reload the new one on filesystem unless process using dlopen, correct?

Shared libraries are not loaded, they are mapped:
http://man7.org/linux/man-pages/man2/mmap.2.html


What problem are you trying to solve?

**Comment by geminijun** [comment]
> > I think the shared libraries are loaded into memory already, it won't reload the new one on filesystem unless process using dlopen, correct?
> 
> Shared libraries are not loaded, they are mapped:
> http://man7.org/linux/man-pages/man2/mmap.2.html
> 
> What problem are you trying to solve?

Sorry, I misunderstood it.
The problem is if any of the shared libraries updated, the old snapshots are useless anymore. Is there any workaround for this? I mean even make it able to restore to old status, maybe save all the old libraries?

**Comment by Snorch** [comment]
@geminijun Sorry for a late response.

CRIU assumes that file-system under processes it dumps _does not change_ between dump and restore.

For instance if some process has open file on the file system and it is in the middle of actively reading this file, CRIU does not dump the whole file. Roughly speaking CRIU only dumps a path to the file and current offset in the file, and on restore we just open this file by path and seek to the right offset. This way the dumped process does not notice dump/restore and continues to read the file. But if you change the file or completely delete it or replace it, CRIU will have nothing else except fail, saying that it can't find proper file.

If we dump all files to images, images would be enormously large, that's why we don't do it.

So you can:
1) save full filesystem snapshot from "post-dump" action script when processes are frozen
or
2) save only libraries and paths to them which you know will be required (or found by ldd) from the same script
Before restoring you would need to temporary restore file system either by switching to snapshot or replacing libraries.
