### ISSUE TITLE
Replace the existing proxy/cache servers on twosigma/criu-image-streamer

### ISSUE THREAD

**Issue by avagin** [checkpoint-restore/criu#1061]
@nviennot implemented a new image proxy which works faster and less buggy than the exiting one:

```
I implemented an external proxy to do high performance checkpoint/restore. It's called
criu-image-streamer.

From what I can tell, the current proxy/cache server most likely harbor more bugs. Once
I open-source criu-image-streamer (within a week or two), my plan is to propose that it replaces
the existing proxy/cache servers.@nviennot implemented a new proxy/cache server and here
is an idea to replace the existing one 

```

The start of this discussion is in
https://github.com/checkpoint-restore/criu/pull/1051#issuecomment-623511160

Cc: @adrianreber @xemul

**Comment by avagin** [comment]
https://github.com/twosigma/criu-image-streamer

**Comment by nviennot** [comment]
I am not clear on how I should add the streamer to the criu project:
1) I can add it to the main criu repo in a subfolder.
2) I can create a new repo at https://github.com/checkpoint-restore/criu-image-streamer

If we go with 1) I could add a Makefile feature flag for compiling the streamer. But then should it be on or off by default? @adrianreber had well founded reservations due to packaging concerns.

In both cases, I will take out the existing proxy/cache servers and update documentation

**Comment by adrianreber** [comment]
From the packaging standpoint I would prefer a separate repository. As long as CRIU and criu-image-server do not require each other during build time I think it makes sense. With good documentation in the wiki and in the man-pages it should be possible for interested users to find criu-image-server even if it is in another repository.

**Comment by avagin** [comment]
@nviennot I created https://github.com/checkpoint-restore/criu-image-streamer. You have the write access to this repo.

**Comment by nviennot** [comment]
Thank you

I'm waiting for approval for transfering the ownership of the reposutiry from our org to yours. Stay tunned.
