### ISSUE TITLE
Hi everyone,

### ISSUE THREAD

**Issue by mind-mind** [checkpoint-restore/criu#1243]
I’m trying to checkpoint the container docker. I cannot use the docker checkpoint. I’m quite sure that it was because of CRIU.

Any suggestion?

Here is an error.
![120062726_806064590226176_5184653886753557053_n](https://user-images.githubusercontent.com/68138683/97135210-440fb700-1782-11eb-9ab3-ccf164290f2f.png)

![120037751_3297638410284981_2994700580323920014_n](https://user-images.githubusercontent.com/68138683/97135206-4114c680-1782-11eb-90e4-b660a27a3d35.png)

**Comment by mind-mind** [comment]
![120221459_261960031630305_683271880059858685_n](https://user-images.githubusercontent.com/68138683/97135262-6275b280-1782-11eb-8b40-f3442d3921a3.png)

**Comment by adrianreber** [comment]
It would be easier if you provide log files instead of screenshots, but there are currently a few problem with docker and Ubuntu concerning CRIU. First of all docker is broken concerning checkpoint/restore (see https://github.com/checkpoint-restore/criu/issues/1223) and then there is always the chance of hitting a Ubuntu only kernel bug (see https://github.com/checkpoint-restore/criu/issues/860).

If you want to try out container checkpointing and restoring you could try Podman on CentOS 8. That should work. (https://criu.org/Podman)

I am closing this as it sounds exactly like #1223
