### ISSUE TITLE
Need to resurrect btrfs testing

### ISSUE THREAD

**Issue by xemul** [checkpoint-restore/criu#133]

**Comment by apinter** [comment]
I do realize that this issue is almost 5 years old, but it would be great to have `btrfs` testing if there isn't yet as it is getting more and more relevant with Fedora switching to it as default fs on F33 Workstation.
Had a run in with criu recently when I tried to checkpoint a podman container on openSUSE. Going to link the issue in case anyone is interested: https://github.com/containers/podman/issues/9318

**Comment by adrianreber** [comment]
Good idea. We can use our existing vagrant setup to boot up Fedora 33. Vagrant uses the cloud image so we need to create a btrfs  and manually mount it. But sounds doable.
