### ISSUE TITLE
runc --criu command not picking up new binary while trying to do pre-dump

### ISSUE THREAD

**Issue by devikrishnar** [checkpoint-restore/criu#1330]
Hi, 

I made some changes in the CRIU code base for testing purposes and I built the new CRIU binary. But when I try to pass it to runc using the command -
`runc --criu "/criu/criu/criu" checkpoint --pre-dump --image-path parent containername`
it still uses the existing previous binary. 

But when I tried the pre-dump command of CRIU - 
`criu pre-dump -t PID --images-dir parent`
the updated binary was used.

Is there anything wrong with the way I am using the` runc --criu` command?

Thanks in advance!

**Comment by adrianreber** [comment]
That does not sound like a CRIU error, but rather a runc problem. There was, however, a short time in runc where the error you described could happen. This was fixed with https://github.com/opencontainers/runc/commit/6f4616dd73bdd9efd35465e857111a36bbea7db8

If you run runc in `--debug` mode you should be able to see which binary it uses:
```
# runc --debug --criu /share/criu/criu/criu checkpoint rhel7 
DEBU[0000] Using CRIU 31600 at: /share/criu/criu/criu   
DEBU[0000] Using CRIU with following args: [swrk 3]     
DEBU[0000] Using CRIU in DUMP mode                     
```

Most importantly check if your version of runc has the commit https://github.com/opencontainers/runc/commit/6f4616dd73bdd9efd35465e857111a36bbea7db8

Closing as this is a runc problem and not a CRIU problem.
