### ISSUE TITLE
Android  has unreachable sharing. Try --enable-external-masters.

### ISSUE THREAD

**Issue by hiyangyue** [checkpoint-restore/criu#1458]
In Android Plantform, I can dump shell process success, but it will fail when I dump Android App Process. The error looks like:
>(00.047096) mnt: Inspecting sharing on 307 shared_id 0 master_id 12 (@./storage/self)
(00.047100) Error (criu/mount.c:947): mnt: Mount 307 ./storage/self (master_id: 12 shared_id: 0) has unreachable sharing. Try --enable-external-masters.
(00.047110) Unlock network
(00.047114) Unfreezing tasks into 1
(00.047117) 	Unseizing 5244 into 1
(00.048427) Error (criu/cr-dump.c:1743): Dumping FAILED.

full log: [dum.log](https://drive.google.com/file/d/1bm13FuNL0mLnD_GVUDuFkrTLKSqoM05E/view?usp=sharing)

---
Kernel Info: 
> Linux version 4.4.192+ (root@VM-236-196-ubuntu) (gcc version 4.9.x 20150123 (prerelease) (GCC) ) #8 SMP PREEMPT Mon Apr 19 19:33:00 CST 2021

Kernel Source: 
>git clone https://android.googlesource.com/kernel/common/
git checkout  da6d147f98d198c3d9059e609ca492a4824d9ef5

criu Version:
> 3.1.3

**Comment by avagin** [comment]
The Android App Process is running in another mount namespace. You need to find out how it was created and then decide how to restore it.

**Comment by Snorch** [comment]
Adding to what @avagin said.

>Mount 307 ./storage/self (master_id: 12 shared_id: 0) has unreachable sharing. 

This mount should either be marked as external(or e.g. root) mount with criu options or you should remove sharing from it.

Your problem is that you have separate mount namespace for you dumped application which has mounts "connected" to mounts on host (have same shared/master id), criu can't resolve this external dependency itself. So either you remove the dependency or you properly describe the dependency to criu.

**Comment by adrianreber** [comment]
Closing. Please re-open if you have further questions.
