### ISSUE TITLE
A problem for using "/proc/pid/map_files/" when dump file map

### ISSUE THREAD

**Issue by geminijun** [checkpoint-restore/criu#1513]
**Description**
If we restored a process in a new pid&mnt namespace, and this process got an "fd" transferred from another process(in a different mnt namespace). CRIU dump(in the same namespace with the target process) will be failed due to can't lookup the mnt_id.

**Steps to reproduce the issue:**
1. Write a program that uses an "fd" transferred from another process, and mmap it.
2. Use CRIU to dump it and then restore it in a new pid&mnt namespace.
3. After the restore, the program got an "fd" transferred from another process(which is in a differnt mnt namespace) and mmap it.
4. Try to use CRIU checkpoint again(in the same pid&mnt namespace), it failed due to following error:
```
Error: Can't lookup mount=20 for fd=-3 path=/mapped_file
Error: Collect mappings (pid: 2990436) failed with -1
Error: Dumping FAILED.
```

**Describe the results you received:**
Failed to checkpoint after restoring it in a new pid&mnt namespace.

**Describe the results you expected:**
Successfully checkpoint the prcess.

**Additional information you deem important (e.g. issue happens only occasionally):**

Actually, I have dive deep into this problem and found the root casue. When CRIU tries to dump a file map. It will open the `/proc/pid/map_files/vma_start-vma_end`(which should link to the real file path) and got the `vm_file_fd`, then read mnt_id from `/proc/self/fdinfo/vm_file_fd`. In the case I described above it will get the mnt_id same with the original process(The one open the file and transfer the fd to the target process), instead of the `mnt_id` that we should see in the new mnt namespace.

Now I have a process restored in a new pid&mnt namespace:
```
root      8900  0.2  0.1 10050540 19436 pts/4  Sl+  16:58   0:00 java A1 1
```
Enter its namespace and check the file map:
```
nsenter -t 8900 -m -p
# ps aux | grep java
root      8667  0.2  0.1 10050540 19436 pts/4  Sl+  16:58   0:00 java A1 1

# lsof -p 8667
java    8667 root    6u   REG              0,19       0  4554167 /mapped_file
# ls -l /proc/8667/map_files/ | grep mapped_file
lrw-------. 1 root root 64 Jun 15 17:03 781600000-781800000 -> /mapped_file
```

Open the file map link and check fdinfo
```
# exec 100< /proc/8667/map_files/781600000-781800000
# cat /proc/$$/fdinfo/100
pos:    0
flags:  0100000
mnt_id: 20
```
**20 is actually the mnt_id from the host mnt namespace.**

If I open the real file path and check the fdinfo:
```
# exec 101< /mapped_file
# cat /proc/$$/fdinfo/101
pos:    0
flags:  0100000
mnt_id: 92
```
This one is correct.

I made a patch to use the real file path instead of the `/proc/pid/maps_files/` seems to work well. Worried if I missed something:

```
diff --git a/criu/proc_parse.c b/criu/proc_parse.c
 index 0842a0e13..679e992ed 100644
 --- a/criu/proc_parse.c
 +++ b/criu/proc_parse.c
 @@ -375,6 +375,8 @@ static int vma_get_mapfile(const char *fname, struct vma_area *vma, DIR *mfd,
  {
         char path[32];
         int flags;
 +       char real_name[PATH_MAX];
 +       int ret;

         /* Figure out if it's file mapping */
         snprintf(path, sizeof(path), "%"PRIx64"-%"PRIx64, vma->e->start, vma->e->end);
 @@ -426,7 +428,20 @@ static int vma_get_mapfile(const char *fname, struct vma_area *vma, DIR *mfd,
                  */
                 flags = O_RDONLY;

 -       *vm_file_fd = openat(dirfd(mfd), path, flags);
 +       /*
 +        * When the process got the fd transfered from another process and maps it,
 +        * Then open the /proc/pid/map_files/vma_start-vma_end will get the mnt_id
 +        * same with the original process who opens it, even the target process now
 +        * is in a different mnt namespace.
 +        * Tried to use the real file path works well
 +        */
 +       ret = readlinkat(dirfd(mfd), path, real_name, sizeof(real_name) - 1);
 +       if (ret < 0) {
 +               *vm_file_fd = openat(dirfd(mfd), path, flags);
 +       } else {
 +               real_name[ret] = '\0';
 +               *vm_file_fd = open(real_name, flags);
 +       }
         if (*vm_file_fd < 0) {
                 if (errno == ENOENT)
                         /* Just mapping w/o map_files link */
```

**CRIU logs and information:**

<details><summary>CRIU full dump/restore logs:</summary>
<p>

```
(paste your output here)
```

</p>
</details>

<details><summary>Output of `criu --version`:</summary>
<p>

```
(paste your output here)
```

</p>
</details>

<details><summary>Output of `criu check --all`:</summary>
<p>

```
(paste your output here)
```

</p>
</details>

**Additional environment details:**

**Comment by avagin** [comment]
@Snorch could you take a look at this?

**Comment by Snorch** [comment]
@geminijun Hi!

> Describe the results you received:
> Failed to checkpoint after restoring it in a new pid&mnt namespace.

Short answer: That's the exact result I would expect in this case, it's a RIGHT behaviour for CRIU.

> I made a patch to use the real file path instead of the /proc/pid/maps_files/ seems to work well.

Your patch is wrong in general (though surely it works for your case as file opened from other mount does not bother your app).

> and mmap it.

Mmap here is actually not important, you would have the same with simple opened file fd.

Some more details:

In linux files on different mounts are not same files, e.g.: readlink result is different. Example:
```
mkdir /mnttest
mount -t tmpfs tmpfs /mnttest
mount --make-private /mnttest
touch /mnttest/testfile
exec 100< /mnttest/testfile
unshare -m
exec 101< /mnttest/testfile
mkdir /mnttest2
mount --move /mnttest /mnttest2
readlink /proc/$$/fd/{100,101}
```
Output:
```
/mnttest/testfile
/mnttest2/testfile
```
One can see that file opened from the first mount namespace didn't change readlink path after moving mount in nested mount namespace, though the file opened in second mount namespace changed the readlink path.

So in case those 100 and 101 were mmaped, your patch would fail to open /mnttest/testfile to restore fd 100 as mounts in first and second mountns has different mountpoints.

There are many other reasons why we need to dump and restore opened/mmaped files from the same mount, if we don't do so we can corrupt application view on the filesystem, even accidentally open different file with
 different content.

So all the above was to convince that CRIU should dump/restore files from/to correct mount. =)

And here comes the real problem of your case, the mount of your file does not belong to the dumped environment (mntns) it means that by design CRIU can't do anything with this file. CRIU does not handle external resources itself. The user should provide all external resources to criu via special options.

You should just use:
```
*--external* **file[**__mnt_id__**:**__inode__**]**::
    Dump an external file, i.e. an opened file that is can not be resolved
    from the current mount namespace, which can not be dumped without using
    this option. The file is identified by 'mnt_id' (a field obtained from
    **/proc/**__pid__**/fdinfo/**__N__) and 'inode' (as returned by
    *stat*(2)).
```

**Comment by geminijun** [comment]
Thank you so much for the detailed explanation. I know what's the best way to do now.

Two more questions:
1) Actually, the reason why I restore it in a new namespace, is because of the infamous PID conflict, my application really doesn't care about the mnt namespace, but it looks like I have to new a new mnt namespace when creating a new PID namespace?

2) For the example you gave me if the process mmap the fd 100&101 before moving the mount, what it will look like after moving the mount?(Don't know how to test it in bash) I guess the "map_files/VMA100 -> /mnttest/testfile", and "map_files/VMA101 -> /mnttest2/testfile ?

What I found, the "/proc/pid/fd" still link to the old path:
```
# ll /proc/$$/fd
total 0
lrwx------. 1 root root 64 Jun 16 10:17 0 -> /dev/pts/4
lrwx------. 1 root root 64 Jun 16 10:17 1 -> /dev/pts/4
lr-x------. 1 root root 64 Jun 16 10:17 100 -> /mnttest/testfile--------------------> shows red becasue it doesn't exist
lr-x------. 1 root root 64 Jun 16 10:18 101 -> /mnttest2/testfile
lrwx------. 1 root root 64 Jun 16 10:17 2 -> /dev/pts/4
lrwx------. 1 root root 64 Jun 16 10:17 255 -> /dev/pts/4
```
And even I write the file from another mnt namespace, it's visible to both fds.
```
# read 0<&101 line
# echo ${line}
104
# read 0<&100 line
# echo ${line}
104
```

And those two files have the same st_dev & the same ino.

I'm confused about what mnt ns is designed for, looks like no matter what mnt ns & file path, as long as the "st_dev"&"ino" are the same, then it's working on the same file, correct?

Then say for the file map VMA100 -> /mnttest/testfile, and CRIU tries to checkpoint/restore, The only differenct is the mnt_id, when you open "map_files/VMA100" and open "/mnttest/testfile" ?Everything else is the same, correct?

**Comment by geminijun** [comment]
@Snorch One more question, in which case `root_ns_mask` will set `CLONE_NEWNS` ?
I found in my case, it didn't set this flag, and so the `mnt_id` won't be saved anyway.
When checkpoint, it only needs the file path, and when restore, just open the file and mmap it.
In my case, we close the file before the checkpoint so the fd table doesn't matter.
So as long as the file is accessable in the new namespace, it doesn't care which mnt ns its in.

And I found if I use `--external` when checkpoint, I have to use `inheritfd` to restore it properly?

**Comment by Snorch** [comment]
@geminijun Hope I answer all your questions =)

>Actually, the reason why I restore it in a new namespace, is because of the infamous PID conflict, my application really doesn't care about the mnt namespace, but it looks like I have to new a new mnt namespace when creating a new PID namespace?

In general one can dump an application from host pid and mntns and then restore it into new pidns and host mntns. But this may lead to problems when this application would later try to access proc (e.g. /proc/<pid_of_another_task>) because it sees proc of host pidns but sees pids of new pidns, which would likely lead to confusion...

So in practice you would likely need to have pidns+mntns. (Never the less having an app running in a full container where the container management always knows about all external resources is always more convenient. You don't care about pid-conflict,)

>I guess the "map_files/VMA100 -> /mnttest/testfile", and "map_files/VMA101 -> /mnttest2/testfile ?

Should be like this, you are right.

>I'm confused about what mnt ns is designed for, looks like no matter what mnt ns & file path, as long as the "st_dev"&"ino" are the same, then it's working on the same file, correct?

Same file, but accessed through different "access points", and CRIU should restore each fd through it's correct "access point".

>does "--external" help?

If file is marked as external, CRIU should just skip this file without trying to open it. But on restore CRIU would expect corresponding external (inheritfd) option to specify the path to the file in host mntns to be able to restore it. --external option just makes CRIU to skip any related lookups and rely on user provided paths on restore.

>in which case root_ns_mask will set CLONE_NEWNS ?

On dump if criu mntns != dumpee mntns CRIU would assume that it need to dump mntns. You can try entering mntns of your application before CRIU dump, so that it skips mounts (without any --external), not sure though that there would be no more pitfalls in the way.

>I have to use inheritfd to restore it properly?

external+inheritfd for files, that's correct.

**Comment by geminijun** [comment]
@Snorch Thanks a lot for your explanations, I'm closing this issue since it's not a problem. Thanks!
