### ISSUE TITLE
docker checkpoint create failed

### ISSUE THREAD

**Issue by CrazycatNY** [checkpoint-restore/criu#1649]
i create a cantainer with "docker run -d --name test --security-opt seccomp:unconfined **** /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done' "

and i try to use docker checkpoint create command and get an error

Error response from daemon: Cannot checkpoint container ny: runc did not terminate sucessfully: criu failed: type NOTIFY errno 0 path= /var/run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/5f321a5b9da20bfd29dcfb9abca324da1cf4abc6675db86bc3c4124fe81c672d/criu-dump.log: unknown

and the criu-dump.log shows:
(10.001106) Error (criu/cr-dump.c:1470): Timeout reached. Try to interrupt: 0
(10.001226) Error (compel/src/lib/infect.c:235): Unseizable non-zombie 681510 found, state D, err -1/4
(10.001243) unix: Unlocking unix stream sockets

why the process state is D，and how can i fix it？

**Comment by mihalicyn** [comment]
Hi @CrazycatNY

state D means Uninterruptible sleep
https://github.com/torvalds/linux/blob/v5.14/fs/proc/array.c#L135
https://github.com/torvalds/linux/blob/v5.14/fs/proc/array.c#L186

you can see task state for any process using `/proc/<pid>/status | grep State`.

CRIU can't dump processes in D-state because such processes unkillable, untracable. In most cases kernel puts tasks in uninterruptible sleep for a short amount of time (common case is I/O things). But sometime it may happen that something goes wrong in the kernel I/O, because of FUSE, NFS (for instance) and in this case process gets blocked inside the kernel.

In your case you just need to recheck if process still in D-state, if so, you need to take a look on `/proc/<pid>/stack` and investigate what happens. Anyway, that's not a CRIU problem.

Alex

**Comment by adrianreber** [comment]
Closing. @CrazycatNY please re-open if you have further questions.

**Comment by flowhub-team** [comment]
My situation involves slow disk performance, leading to processes entering the 'D' state while waiting for I/O operations. During this state, if a checkpoint is attempted, errors like 
(10.001106) Error (criu/cr-dump.c:1470): Timeout reached. Try to interrupt: 0
(10.001226) Error (compel/src/lib/infect.c:235): Unseizable non-zombie 681510 found, state D, err -1/4
 occur. Since the 'D' state typically resolves quickly, is there a way for CRIU to wait for the 'D' state to end before proceeding with the checkpoint?
