### ISSUE TITLE
Restore fails after reboot

### ISSUE THREAD

**Issue by kkors** [checkpoint-restore/criu#1716]
I dumped a script that I wrote using criu and then issued a CronJob to restore its state at reboot. Cron calls a script which runs criu restore.
I then rebooted my VM and the CronJob does run but eventually fails at the restore command.
I get an error log like this (redirected into a file so I can read it afterwards):
```
﻿Error (criu/util.c:635): exited, status=1
Error (criu/util.c:635): exited, status=1
Warn  (criu/kerndat.c:1205): CRIU was built without libnftables support
Error (criu/pstree.c:401): Current gid 1006 intersects with pid (255) in images
```
I couldn't find any information on the last Error listed here.
Running the script in the same session without rebooting works fine though?

**Comment by adrianreber** [comment]
I have not seen this error before. @checkpoint-restore/maintainers any ideas how solve this?

**Comment by rst0git** [comment]
This error message was introduced recently in https://github.com/checkpoint-restore/criu/commit/7e6a1a7011b404fbf0108b062bda118e9a696b60.

@Snorch suggested in https://github.com/checkpoint-restore/criu/issues/1332

> So probably the answer here is that -j option should not be used when dumping too much processes.

**Comment by PavloMykhailyshyn** [comment]
I recently faced the same problem.
How can I overcome this problem in case of dumping several processes (e.g. ~500)?
My application needs to traverse some running processes and dump them. After the reboot application restores created dumps automatically.
What is the best practice in such a case? How can I achieve my goal?
dump
`/usr/sbin/criu dump --images-dir /var/images/image1143123 --shell-job --tcp-established --ext-unix-sk --tree 1143123`
restore
`/usr/sbin/criu restore --images-dir /var/images/image1143123 --shell-job --tcp-established --ext-unix-sk --restore-detached`

**Comment by PavloMykhailyshyn** [comment]
if I do not provide `--shell-job` the CRIU fails
The root process 1143123 is not a session leader. Consider using --shell-job option

**Comment by PavloMykhailyshyn** [comment]
dumping processes one by one would be a performance bottleneck

**Comment by PavloMykhailyshyn** [comment]
so as I understand correctly, the main reason why CRIU fails is due to doing a lot of dumps/restores simultaneously.
Am I right?

**Comment by kkors** [comment]
The error persists even without reboot and without trying to dump many processes. In fact I implemented an example where I tried to dump only one process:

example.sh:
```
#!/bin/bash

full_path=$(realpath $0)
dir_name=$(dirname $full_path)
cd $dir_name
output="$dir_name/example.txt"
> $output

echo hello world > $output
sleep 120
echo foobar >> $output
```
 which basically only writes 'hello world' to example.txt, waits 120sec, then adds 'foobar'


c_example shall dump the process inside the cp_dir directory while it is waiting:
```
#!/bin/bash

full_path=$(realpath $0)
dir_name=$(dirname $full_path)
cd $dir_name
cp_dir="$dir_name/cp_dir"

errlog="$dir_name/errlog.txt"
> $errlog
echo Checkpoint: >> $errlog
exec 2>> $errlog

process=$(pgrep -x example.sh)

mkdir $cp_dir
sudo criu dump -D $cp_dir -t $process -j
```


then r_example.sh restores the process so it can proceed to write to example.txt:
```
#!/bin/bash

full_path=$(realpath $0)
dir_name=$(dirname $full_path)
cd $dir_name
cp_dir="$dir_name/cp_dir"

errlog="$dir_name/errlog.txt"
echo Restore: >> $errlog
exec 2>> $errlog

sudo criu restore -D $cp_dir -j
```


When I do all of this manually through the terminal it works, example.txt looks exactly like it should and there are no errors in errlog. But when I schedule a cronjob, the task fails, giving me the exact error
`Error (criu/pstree.c:401): Current gid 1006 intersects with pid (255) in images`
as mentioned above, only with the gid varying. It happens on restore.
Like @PavloMykhailyshyn already mentioned it is not possible to not provide the -j option because the `process <pid> is not a session leader` error occurs.

At this point my crontab looks like this:
```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 22 * * * /home/<user>/examplescript/example.sh
11 22 * * * /home/<user>/examplescript/c_example.sh
12 22 * * * /home/<user>/examplescript/r_example.sh
```
With user being my username.

It seems to be a problem which only occurs when I call criu via a cronjob. How can I get it to work without calling criu manually every time?

**Comment by adrianreber** [comment]
Why are you using a cronjob to restore the processes after reboot?

**Comment by kkors** [comment]
For the real use case I want to use criu in I need to automate the process (it needs to happen right after every reboot) and I figured using a cronjob to do it would be the best option.

**Comment by adrianreber** [comment]
Try it with a systemd oneshot service. I am pretty sure that worked for me. cronjob seems strange.

https://www.redhat.com/en/blog/using-criu-upgrade-vpn-servers-kernel-without-dropping-connections

**Comment by adrianreber** [comment]
No, in that article I used rc.local which is probably run by a systemd oneshot service.

**Comment by PavloMykhailyshyn** [comment]
I will explain the problem in more detail
 I have a systemd service that runs on system startup.
 This service starts CRIU after receiving appropriate events from the network.
 After that, this service goes through all processes and finds corresponding ones for the dump.
 This service launches CRIU for each process simultaneously.
 When all dumps are complete, the service ends. The system gets rebooted or whatever.
 The service starts again and goes through each dump folder. It runs CRIU on every image simultaneously.
 But for all of the processes that have been dumped, CRIU is unable to perform a restore due to this issue
` Current gid <id> intersects with pid (id) in images`
I will ask the question again
the main reason why CRIU fails is due to doing a lot of dumps/restores simultaneously.
Am I right?

**Comment by adrianreber** [comment]
> I will ask the question again
> the main reason why CRIU fails is due to doing a lot of dumps/restores simultaneously.
> Am I right?

I at least don't know, sorry. Never heard of a use case like yours before.

**Comment by PavloMykhailyshyn** [comment]
I tried to dump every process one by one and then performed a restore exactly in the same manner.
The same error occurred :(
I do not really understand how can this problem be resolved.
`Error (criu/pstree.c:401): Current gid 2443411 intersects with pid (255) in images`
What else can you suggest to solve this issue?

**Comment by PavloMykhailyshyn** [comment]
basically, I did not say one important thing
this service dumps and restores processes spawned by itself.
so setsid for newly forked processes fixed the problem

**Comment by kkors** [comment]
> No, in that article I used rc.local which is probably run by a systemd oneshot service.

@adrianreber Thank you for the suggestion, I tried it that way but I get the exact same error as before:
`Error (criu/pstree.c:401): Current gid 815 intersects with pid (255) in images`

Same problem: When I run it manually everything works. When I try to automate it and the systemd service calls the script right after reboot I get this error.

**Comment by kkors** [comment]
The gid number always changes in this error but the pid (255) in images is always the same.

**Comment by Snorch** [comment]
> if I do not provide --shell-job the CRIU fails
> The root process 1143123 is not a session leader. Consider using --shell-job option

Let's call this "external session" problem. There are other ways except --shell-job to handle these error, criu error just offers the simple one, but it does not mean that this simple one works in all the cases.

If you get `The root process <pid> is not a session leader. Consider using --shell-job option` choose one of:

1) add --shell-job so that external session dependency is autoresolved
2) initially get rid of external dependency, when start the process you plan to dump later, use setsid and closed stderr, stdin and stdout initially
3) initially run the process you plan to dump in container which supports c/r (podman, openvz, e.t.c.)

> so as I understand correctly, the main reason why CRIU fails is due to doing a lot of dumps/restores simultaneously.
> Am I right?

Yes you are. Dumping processes without container (pid namespace) has a "pid collision" problem, if you dumped process with PID
and now you restore it and some other process (the process group leader in your case) already had taken this PID you would fail. And this race becomes more frequent if you do multiple separate restores.

> so setsid for newly forked processes fixed the problem

This only fixes "external session" problem but does not fix "pid collision"

> The gid number always changes in this error but the pid (255) in images is always the same.

I believe the gid in images always changes too, but it is not printed.


To conclude, to fix both "external session" and "pid collision" problems you should use variant (3) - run processes in containe
rs, there is just no other way to fix "pid collision" problem.

**Comment by kkors** [comment]
@Snorch Can you maybe explain your second approach to solving the "external session" problem (getting rid of external dependencies) in reference to how I could implement it in my example.sh program?

**Comment by Snorch** [comment]
> explain your second approach

Let me illustrate it by taking your unchanged example.sh

```
[root@fedora /]# cat /tmp/example/example.sh
#!/bin/bash

full_path=$(realpath $0)
dir_name=$(dirname $full_path)
cd $dir_name
output="$dir_name/example.txt"
> $output

echo hello world > $output
sleep 120
echo foobar >> $output
```

Try 1:

```
# term 1
[root@fedora /]# /tmp/example/example.sh

# term 2
[root@fedora example-dump]# criu dump -t $(pgrep example.sh) -vvvv 2>&1 | grep Error
(00.015128) Error (criu/tty.c:1812): tty: Found dangling tty with sid 2171974 pgid 2173854 (pts) on peer fd 0.
(00.015214) Error (criu/cr-dump.c:1788): Dumping FAILED.
```

Hm, external tty => let's just close standard io fds.

Try 2:

```
# term 1
[root@fedora /]# /tmp/example/example.sh &>/dev/null </dev/null

# term 2
[root@fedora example-dump]# criu dump -t $(pgrep example.sh) -vvvv 2>&1 | grep Error
(00.019989) Error (criu/pstree.c:296): The root process 2174145 is not a session leader. Consider using --shell-job option
(00.020095) Error (criu/cr-dump.c:1788): Dumping FAILED.
```

Hm, they ask us to use --shell-job, but we are smart and want instead to get rid from external session.

Try 3:

```
# term 1
[root@fedora /]# setsid /tmp/example/example.sh &>/dev/null </dev/null

# term 2
[root@fedora example-dump]# criu dump -t $(pgrep example.sh) -vvvv 2>&1 | grep Error
[root@fedora example-dump]#
```

Dumped fine, let's try restore.

```
# term 2
[root@fedora example-dump]# criu restore -vvvv 2>&1 | grep Error
<hangs>

# term 1
[root@fedora /]# pgrep example.sh
2174494
<~120 sec later>
[root@fedora /]# cat /tmp/example/example.txt 
hello world
foobar
```

All restored fine. So at least on bash it can be done by setsid + /dev/null fd redirect _outside_of your example.sh.

>> so setsid for newly forked processes fixed the problem
>
> This only fixes "external session" problem but does not fix "pid collision".

But I need to mention _again_, this does not solve "pid collision" problem in any way.

**Comment by PavloMykhailyshyn** [comment]
Should I be concerned about these errors?
`sh: 0: getcwd() failed: No such file or directory`
`Error (criu/image.c:475): Unable to open stats-restore: No such file or directory`
It happens during the restore (the process successfully restored)
I`m doing it with the help of criu-ns

**Comment by PavloMykhailyshyn** [comment]
I noticed one strange error
when i run the dump with criu and it succeeds, criu returns 0
but when i run criu-ns and it succeeded too but the return code is now 5
I checked the logs for both criu and criu-ns everything is the same (dump successful)
How can I tell if a process has completed successfully?

**Comment by PavloMykhailyshyn** [comment]
@Snorch Can you help please?

**Comment by Snorch** [comment]
> I noticed one strange error when i run the dump with criu and it succeeds, criu returns 0 but when I run criu-ns and it succeeds too - return code is now 5 I checked the logs for both criu and criu-ns everything is the same (dump successful) How can I tell if a process has completed successfully?

Just for history, was a separate issue, handled here https://github.com/checkpoint-restore/criu/issues/1739

**Comment by PavloMykhailyshyn** [comment]
@Snorch  and @rst0git I would kindly ask you to shed a light on this
What to do if a dump or restore takes too long
e.g. more than 10 minutes (if criu is waiting in an infinite loop or something weird happens)
That's why I'm interested in killing the criu process in order to be able to proceed with other tasks that my program is doing.
If I encountered such a situation, what kind of signal can I send to criu to stop its work properly (or maybe there is something else to force criu to finish its work)?

**Comment by adrianreber** [comment]
@PavloMykhailyshyn did you try `kill -9`. That works for me if CRIU hangs during debugging.

**Comment by PavloMykhailyshyn** [comment]
The main question here is what is the safest way to interrupt criu in case something weird happens (as you said criu hangs)?
So the criu is possibly able to free some resources or etc.
SIGKILL sounds like a last chance :)

**Comment by PavloMykhailyshyn** [comment]
If there's only one way to end criu while it's hanging is SIGKILL, is it safe to do that? (during dump and restore)

**Comment by adrianreber** [comment]
> is it safe to do that?

Anything specific you are thinking about? The dump and restore would be unsuccessful, but not unsafe. Still not sure what it means :wink:

**Comment by PavloMykhailyshyn** [comment]
I do not know the internals of criu, but my concern is e.g. criu tries to restore and it hangs when the process is half restored.
I killed criu. How about this half restored process? What about their resources and so on. (OS will clean everything up?)

**Comment by kkors** [comment]
@Snorch Thank you this worked for me and not using the --shell-job option actually also resolved the 'pid-collision' error when trying to call criu restore at boot. Would consider my issue fixed.

**Comment by kkors** [comment]
I would like to reopen the issue.
I tried running my program on a different system and it gives me two other errors during Restore.

The first one is `Error (criu/util.c:636): exited, status=1`
This one can happen during Restore and sometimes during Checkpoint too although not as often.

The second one is
```
Error (criu/cr-restore.c:1450): Can't fork for 1742: File exists
Error (criu/cr-restore.c:2470): Restoring FAILED.
```
This obviously happens during Restore with the number 1742 being the PID of the checkpointed process. (Note that the error is thrown independently of wether the Checkpoint succeded)

Both errors only happen occassionally (sometimes Checkpoint and Restore function normally) but often enough that it poses a problem. Often Restore fails but oddly enough the program continues nonetheless which probably means that not all of the information has been restored but enough for it to proceed.

The first error does not give me an error message so that I cannot work out what's wrong but its always the same line in criu/util.c (636) that fails.
For the second error I don't really understand what it says (Maybe that the PID is already in use? But that wouldn't make any sense for the program to then continue) and I haven't found anything on that error message on the web.

**Comment by adrianreber** [comment]
We cannot say much about the first error without the full log using `-v4`.

The second error is because another process is already using the PID. This is the classical PID collision problem that can happen with CRIU. This error only happens during restore. Not much you can do about it besides starting process in PID namespaces or containers.

> For the second error I don't really understand what it says (Maybe that the PID is already in use? But that wouldn't make any sense for the program to then continue) and I haven't found anything on that error message on the web.

Not sure what you are tying to say? Why does it not make any sense? It totally makes sense from my point of view.

**Comment by kkors** [comment]
Ok, so for the `Error (criu/util.c:636): exited, status=1`Error I will provide a full log using -v4 for one restore in which it happened. The attached file contains the error log.
[ErrorMessage.txt](https://github.com/checkpoint-restore/criu/files/8064756/ErrorMessage.txt)
The error seems to happen pretty early in execution and oddly enough at the end it says that the Restore finished successfully?

> Not sure what you are tying to say? Why does it not make any sense? It totally makes sense from my point of view.

I don't understand why the checkpointed process sometimes (not always) continues after the restore failed due to the PID collision problem. I mean it shouldn't restore the program right? How can it load nonetheless?
Also sometimes the restoring process kind of stops inbetween. And when I abort it you would think that the restoration fails again but in this case my program again seems to continue just like that. 
I could probably abort it every time it hangs up but it wouldn't make any sense because I'm trying to automate the checkpoint restore process. Also aborting the restoration could result in losing dependencies in my program.

**Comment by adrianreber** [comment]
> Ok, so for the `Error (criu/util.c:636): exited, status=1`Error I will provide a full log using -v4 for one restore in which it happened. The attached file contains the error log.
> [ErrorMessage.txt](https://github.com/checkpoint-restore/criu/files/8064756/ErrorMessage.txt)
> The error seems to happen pretty early in execution and oddly enough at the end it says that the Restore finished successfully?

Yes. That is no real error. Something failed during early feature detection. CRIU tries to load netfilter modules to test for certain functions. This only happens during the first run after a boot as long as `/run/criu.kdat` does not exist.



> I don't understand why the checkpointed process sometimes (not always) continues after the restore failed due to the PID collision problem.

It should not. If there is a PID collision it will abort.

> I mean it shouldn't restore the program right? How can it load nonetheless?

It cannot. I assume from your previous comments that "sometimes" means during some boot up cycles it works and sometimes it does not. Sometimes processes are created in a different order and are using different PIDs. So sometimes you might succeed with the restore because the necessary PIDs are not use and sometimes it fails because the PIDs are in use.

It still all makes sense to me.

If I have a system with PID 1, 2, 3, 4 and now I checkpoint PID 4 to be automatically be restored on reboot. The processes 1, 2, 3 will be started as usual by the boot up and now I want to restore PID 4. I start CRIU to do the restore and now CRIU will use PID 4. Now CRIU as PID 4 wants to restore the process with PID 4. It uses clone3() to create a new process with PID 4 and it fails because currently CRIU uses PID 4.

> Also sometimes the restoring process kind of stops inbetween. And when I abort it you would think that the restoration fails again but in this case my program again seems to continue just like that.
> I could probably abort it every time it hangs up but it wouldn't make any sense because I'm trying to automate the checkpoint restore process. Also aborting the restoration could result in losing dependencies in my program.

Not sure what you mean here.

Anyway, PID collisions are hard to solve. Especially during boot up where all the initial processes are using the low PIDs one after another without any wholes.

Please always include the log files for failures you are seeing. It is not completely clear what the problem is. From my point of view it works correctly. If it fails due to a PID collision it is still correct even if that is not what you wanted.

Also try to be more precise. Show also us a list of running processes during the restore failure (`ps aux` or something like that).

**Comment by kkors** [comment]
Ok, I resolved the error. 

My problem was slightly different than from what you described but it was a misbehaviour of my program and not of CRIU.
(in fact I resolved the problem as I was writing a reply and I got a new idea to try something different so indirectly you helped me nonetheless, thank you)

**Comment by adrianreber** [comment]
Good that you found a solution.
