### ISSUE TITLE
cgroup related tests seem to be failing more often in CI

### ISSUE THREAD

**Issue by adrianreber** [checkpoint-restore/criu#1774]
```
2022-03-11T14:49:33.7079636Z b'(00.022093) cg: adding cgroup /proc/self/fd/15/docker/41af214ff35599b069c697d142ceea1813ac16aceb1cc6b389cdc72d72120cce'
2022-03-11T14:49:33.7080078Z b'(00.022301) cg: adding cgroup /proc/self/fd/15/'
2022-03-11T14:49:33.7080558Z b'(00.022429) cg: adding cgroup /proc/self/fd/15/docker/41af214ff35599b069c697d142ceea1813ac16aceb1cc6b389cdc72d72120cce'
2022-03-11T14:49:33.7081009Z b'(00.022557) cg: adding cgroup /proc/self/fd/15/subcg00/subsubcg'
2022-03-11T14:49:33.7081501Z b'(00.040339) Error (criu/cgroup.c:587): cg: Unable to create the cgroup (name=zdtmtst.defaultroot) file system: Resource busy'
2022-03-11T14:49:33.7082051Z b'(00.040374) Error (criu/cgroup.c:715): cg: failed walking /proc/self/fd/-1/ for empty cgroups: No such file or directory'
```

Recently I have seen more test failures concerning cgroup in CI. CI seems to have changed to a 5.13 although I am not sure that is related.

The error is easy to reproduce and I can see it locally about 10% of the time.

It seems to not happen if I disabled the new mount API support.

I see that `ret = sys_fsconfig(fsfd, FSCONFIG_CMD_CREATE, NULL, NULL, 0);` sometimes returns `EBUSY`. I tried to wrap it in a loop to retry if it fails with `EBUSY`, but the second time it then fails with `EINVAL`. For some reason the kernel behaves differently if I repeat the following steps: `fsopen(), fsconfig(), fsconfig(), close()`.

**Comment by avagin** [comment]
@mihalicyn could you take a look at this?

**Comment by minhbq-99** [comment]
I try to investigate this issue and find out that in the error case

https://github.com/checkpoint-restore/criu/blob/cc4df23fa53429d351a79ba0217a4a3f3944759f/test/zdtm_mount_cgroups#L7

We find `zdtmtst.defaultroot` in /proc/self/cgroup so we exit and don't create new controller. However, later this controller is somehow deleted. Later `fsconfig(FSCONFIG_CMD_CREATE)` with the context name `zdtmtst.defaultroot`, this syscall will call `cgroup1_get_tree`, the `cgroup1_root_to_use` cannot find the cgroup root with name `zdtmtst.defaultroot`. As a result, `restart_syscall` is called

https://github.com/torvalds/linux/blob/master/kernel/cgroup/cgroup-v1.c#L1246

I don't understand the restart syscall mechanism but I guess that the current syscall handler will continue. When the handler returns, that syscall is called again with the exact argument. With that assumption, the error is returned in `cgroup1_get_tree` propagate to `vfs_get_tree`

https://github.com/torvalds/linux/blob/master/fs/fsopen.c#L232

And the phrase in fs context is set to failed

https://github.com/torvalds/linux/blob/master/fs/fsopen.c#L267

In the restart syscall handler, because the phrase of fs context is failed EBUSY is returned 

https://github.com/torvalds/linux/blob/master/fs/fsopen.c#L227

**Comment by avagin** [comment]
hmm. can it be that another zdtm.py is running on the same host? In this case, https://github.com/avagin/criu/commit/9aba5ae055ac6e1c16ce1d74f2cbd86a0212b239 has to fix the issue.

**Comment by minhbq-99** [comment]
Hi, I submit a patch to Linux kernel

https://lore.kernel.org/lkml/20220403135717.8294-1-minhquangbui99@gmail.com/T/#u

It looks like a controller leak but I'm not sure whether it is an actual bug or the expected behavior
