### ISSUE TITLE
Restore fails: no file

### ISSUE THREAD

**Issue by elchead** [checkpoint-restore/criu#1854]
**Description**
I'm trying to restore a container with tcp connection and created a config /etc/criu/runc.conf containing the following lines:
```
tcp-established
tcp-close
```

**Steps to reproduce the issue:**
1. checkpoint container with tcp connection
2. restore container

**Describe the results you received:**
When restoring the container, I get an error complaining about missing files (see log):
```
(00.102544)      1: inet: 	Restore: family AF_INET    type SOCK_STREAM    proto IPPROTO_TCP      port 55236 state TCP_ESTABLISHED  src_addr 172.16.179.158
(00.102575)     18: Error (criu/files-reg.c:2143): Can't open file var/tmp/data/9cf918e5-7f9d-4a61-89b3-ea33a25a64fc/dev_rfc.log on restore: No such file or directory
(00.102585)     18: Error (criu/files-reg.c:2086): Can't open file var/tmp/data/9cf918e5-7f9d-4a61-89b3-ea33a25a64fc/dev_rfc.log: No such file or directory
(00.102588)     18: Error (criu/files.c:1200): Unable to open fd=3 id=0x1e
```

**CRIU logs and information:**
attached as file

</p>
</details>

<details><summary>Output of `criu --version`:</summary>
<p>

```
3.16.1
```

</p>
</details>

<details><summary>Output of `criu check --all`:</summary>
<p>

```
criu check --all
Warn  (criu/cr-check.c:1273): clone3() with set_tid not supported
Error (criu/cr-check.c:1315): Time namespaces are not supported
Error (criu/cr-check.c:1325): IFLA_NEW_IFINDEX isn't supported
Warn  (criu/cr-check.c:1347): Pidfd store requires pidfd_getfd syscall which is not supported
Warn  (criu/cr-check.c:1368): Nftables based locking requires libnftables and set concatenations support
Looks good but some kernel features are missing
which, depending on your process tree, may cause
dump or restore failure.
```

</p>
</details>

**Additional environment details:**
[restoreN.log](https://github.com/checkpoint-restore/criu/files/8532342/restoreN.log)

**Comment by rst0git** [comment]
> I'm trying to restore a container with tcp connection

@elchead What commands are you using to checkpoint/restore the container?

> Error (criu/files-reg.c:2143): Can't open file var/tmp/data/9cf918e5-7f9d-4a61-89b3-ea33a25a64fc/dev_rfc.log on restore: No such file or directory

This error indicates that CRIU fails when restoring a file descriptor for `dev_rfc.log` because the file does not exist. This may happen, for example, if `/var/tmp/data` is not a tmpfs mountpoint, and the root-filesystem changes of the container have not been restored.

AFAIK, containerd and Docker do not currently support checkpoint/restore of rootfs changes. In this case you can mount a tmpfs at `/var/tmp` in the container as a workaround: `docker run --tmpfs /var/tmp ...`

Alternatively, you can use [cri-o](https://github.com/cri-o/cri-o/pull/4199) or [Podman](https://criu.org/Podman) as they have support for checkpoint/restore of rootfs changes.

**Comment by elchead** [comment]
@rst0git thanks! I'm using containerd and just mounted it as tmpfs:
```
df -T /var/tmp/data/
Filesystem     Type  1K-blocks  Used Available Use% Mounted on
tmpfs          tmpfs  65962496 63652  65898844   1% /var/tmp/data
```
Unfortunately, the error still persists. Is there any other way or possible issue to fix with containerd? I cannot easily switch the container runtime, because I made custom changes.

**Comment by elchead** [comment]
It's fixed. In addition to a `tmpfs` it also must not be a bind mount. Kubernetes mounts `emptyDir` volumes through binding.
The solution was to mount a storage volume instead (e.g. PV in Kubernetes).
