### ISSUE TITLE
Cross Compilation for ARM

### ISSUE THREAD

**Issue by sakgoyal** [checkpoint-restore/criu#1986]
I am trying to compile CRIU for ARM (Raspberry Pi 3b+) on my x86 windows laptop through WSL2. I am looking at the cross compilation page on the website and it seems like it is out of date. the url for the toolchain binary does not exist anymore so those instructions no longer work. 

How can I cross compile CRIU for my ARMv8 Pi 3B+ on my x86 computer through WSL2

**Comment by adrianreber** [comment]
Please take a look how we cross compile during CI runs: https://github.com/checkpoint-restore/criu/blob/criu-dev/.github/workflows/cross-compile.yml

**Comment by thesaadmemon** [comment]
@sakgoyal did you manage to get it working?

**Comment by sakgoyal** [comment]
sorry ive been a little busy so I havent gotten around to it. but also, I'm not familiar with how github actions work or how CI/CD works so any help with that (directly or through other resources) would be greatly appreciated.

**Comment by thesaadmemon** [comment]
I did compile the kernel with the pre-required kernel features, however, it looks like something is still missing

OS: Raspbian 32-bit; Kernel-Version: 5.15.76-v7l; CRIU Version: v3.17.1

Output: 

root@raspberrypi:~# criu check
Error (criu/kerndat.c:508): Unexpected error from memfd_create("", MFD_HUGETLB): Function not implemented
Error (criu/kerndat.c:1577): kerndat_has_memfd_hugetlb failed when initializing kerndat.
Error (criu/crtools.c:260): Could not initialize kernel features detection.

**Comment by adrianreber** [comment]
Maybe you forgot to enable support for MEMFD? `CONFIG_MEMFD_CREATE=y`

**Comment by adrianreber** [comment]
Not sure. The error message seems to point to that `memfd_create()` is not available.

**Comment by minhbq-99** [comment]
The error seems because `memfd_create` is available but `MFD_HUGETLB` flag is not but the returned error from `memfd_create` is not expected. Currently, we expect to get `EINVAL` and `ENOENT` in those cases.
https://github.com/checkpoint-restore/criu/blob/d3ed3e90876964334526000f275c6f13cbf2e856/criu/kerndat.c#L490-L511
For quick fix, you can add `ENOSYS` to the errno list here
https://github.com/checkpoint-restore/criu/blob/d3ed3e90876964334526000f275c6f13cbf2e856/criu/kerndat.c#L503
Can you give me the link to your kernel source and libc as we may call `memfd_create` through libc and sometimes kernel supports that flag but libc still returns error?

**Comment by thesaadmemon** [comment]
@minhbq-99 

Thank you for your response.

For Linux Kernel: https://github.com/raspberrypi/linux
For libc I'm not sure, but I was using the latest Raspbian.

**Comment by minhbq-99** [comment]
It's weird because if the `memfd_create` is not available (ENOSYS) we skip the check for `memfd_create(MFD_HUGETLB)`. But as your log, it seems `memfd_create` is available but MFD_HUGETLB flag is not supported and the error is unexpectedly ENOSYS. This error AFAIK is not popular in syscall handler when that syscall is actually available. Anyway, I create a PR to add ENOSYS to the check, welcome any other opinions here.
