### ISSUE TITLE
Can't dump a pid namespace without the process init

### ISSUE THREAD

**Issue by Carol-code2222** [checkpoint-restore/criu#2084]
I'm making an attempt:

1. Start a Docker container: 

[root@localhost ~]# docker run -d --name looper test3 /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'

2. Inside the container, can see:

[root@localhost ~]# docker exec -it looper bash

[root@bbe31fbb7dd8 /]# ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.0   4032  3040 ?        Ts   12:19   0:00 /bin/sh -c i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done
root          41  0.0  0.0   2612  1540 ?        T    12:20   0:00 sleep 1

3. Outside the container, can see:

[root@localhost ~]# docker ps
CONTAINER ID   IMAGE      COMMAND                  CREATED              STATUS              PORTS     NAMES
bbe31fbb7dd8   hcetest3   "/bin/sh -c 'i=0; wh…"   About a minute ago   Up About a minute             looper

[root@localhost ~]# cat /sys/fs/cgroup/cpuset/docker/bbe31fbb7dd8d1bd0291548603c18158d87c6cb4893d5713e4c15104f19759fe/tasks
280344
280416

[root@localhost ~]# ps aux | grep 280344 | grep -v grep
root      280344  0.0  0.0   4032  3040 ?        Ts   12:19   0:00 /bin/sh -c i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done

[root@localhost ~]# ps aux | grep 280416 | grep -v grep
root      280416  0.0  0.0   2612  1540 ?        T    12:20   0:00 sleep 1

4、I'm trying to use criu dump these two processes pid:280344 and pid:280416 outside the container.

[root@localhost ~]# criu dump -D imgdir-$pid -j -t $pid --ext-mount-map auto --enable-external-masters --leave-stopped  -vvvv -o ../dump-$pid.log;

The first process 280344 dumps successfully, the log is shown in: dump-280344.log.

[dump-280344.log](https://github.com/checkpoint-restore/criu/files/10753148/dump-280344.log)

However, the second process 280416 dumps failed. the error log as show in : dump-280416.log.

[dump-280416.log](https://github.com/checkpoint-restore/criu/files/10753125/dump-280416.log)

what means "Can't dump a pid namespace without the process init"？Is there a method to resolve this error.

**Comment by adrianreber** [comment]
> what means "Can't dump a pid namespace without the process init"

When dumping processes with a (non-host) PID namespace, the init process (1) always needs to be part of the checkpoint, because CRIU cannot restore the PID namespace if PID 1 is missing. No PID namespace can exist without PID 1. CRIU stops here because restore is impossible.

> Is there a method to resolve this error.

You can tell CRIU that you want to checkpoint this process out of the PID namespace and into a new PID namespace. This means that you manually need to create a PID namespace before restoring and tell CRIU to use that PID namespace. 

See https://github.com/checkpoint-restore/criu/tree/criu-dev/test/others/ns_ext for how CRIU tests the checkpointing out of a PID namespace and restoring into another PID namespace.
