### ISSUE TITLE
Need UFFD-based memory changes tracker

### ISSUE THREAD

**Issue by avagin** [checkpoint-restore/criu#218]
```
[root@fc24 criu]# python test/zdtm.py run -t zdtm/transition/shmem  --pre 3
=== Run 1/1 ================

======================== Run zdtm/transition/shmem in h ========================
Start test
./shmem --pidfile=shmem.pid --outfile=shmem.out
Run criu pre-dump
Run criu pre-dump
Run criu pre-dump
Run criu dump
Run criu restore
Send the 15 signal to  24
Wait for zdtm/transition/shmem(24) to die for 0.100000
############### Test zdtm/transition/shmem FAIL at result check ################
Test output: ================================
17:30:19.480:    24: FAIL: shmem.c:75: checksum mismatch: 5aa13000 5c625000
 (errno = 11 (Resource temporarily unavailable))

 <<< ================================
```

To: @fbocharov @eabatalov

**Comment by avagin** [comment]
Here is the test: https://patchwork.criu.org/series/571/

**Comment by eabatalov** [comment]
Andrew thank you you for spotting issues with forked and dead process and anon shmem dumping. It looks like a bug for me. I'll take a look and think about possible solutions on this weekend.

About "shmem: Swap out anonymous shared pages before reading pagemap" patch.
I don't understand why "shmem_swapout" is called swapout because it really doesn swapping in.
Also there is no guarantee that swapped in page would stay in RAM until we dump it in cr_dump_shmem(). Anon shmem pages locking (mlock) should work ok. But it has too big maximum RAM usage.
In "shmem: use mincore page status bit with anon shared mem dumping" commit message we can see that currently we can't stop using mincore for anon shmem dumping even when all the pages are swapped in.
Also __parasite_dump_pages_seized where you're calling shmem_swapout() is called for each process in ps tree so we can do swapping in of the same anon shared mem vma >1 times.

Please correct if I am not right somewhere.

**Comment by avagin** [comment]
> About "shmem: Swap out anonymous shared pages before reading pagemap" patch.

@cyrillos misunderstood me and then he asked to drop this patch, because it actually doesn't work.

mincore returns zero for swapped pages and criu doesn't dump them. I suggested to use pagemap instead of mincore, but we need to access all pages to get correct infromation from pagemap.

**Comment by cyrillos** [comment]
Actually the access to the pages data cause kernel to swapin the pages, the problem was that I simply munmap too early. I think the proper fix should be done on pagemap-cache.c level, where when anon shared VMA passes in we need to access the pages before filling the pagemap.

Meanwhile for vz7 CRIU I did a fast fix https://src.openvz.org/projects/OVZ/repos/criu/commits/01add4185263e81e7fdfb357196bbd66a2dfbc02

**Comment by eabatalov** [comment]
@cyrillos I've understood what this thread is about. Yes I am agree with the new logic in your patch https://src.openvz.org/projects/OVZ/repos/criu/commits/01add4185263e81e7fdfb357196bbd66a2dfbc02

**Comment by eabatalov** [comment]
@avagin @xemul 
Now we have two cases where current pagemap based anon shmem changes tracking doesn't work. The first case with many mremaps is implemented in zdtm/transition/shmem test. Another another one with fork:
1. Fork a process and inherit anon shmem region
2. Modify some data in the region in forked process
3. Forked process exit

Considering this 2 cases it turns out that pagemaps don't provide enough information about anon shmem pages state. So current pagemap based implementation has design flow and anon shmem pages tracking should be reworked and based on other approaches such as effective comparison of page contents in previous dump and current dump. In https://src.openvz.org/projects/OVZ/repos/criu/commits/01add4185263e81e7fdfb357196bbd66a2dfbc02 we already touch each page from dumper process. Adding pages content comparison would expand this.
I don't have time now to do the rework. Is it urgent to implement?

Also old mincore based approach that doesn't have anon shmem changes tracking won't work properly when we:
1. map 1MB anon shmem first
2. fill it with data
3. mremap it to 4KB.
4. Do cr.
5. mremap back to 1MB.
We'll lose 1MB-4KB of data after cr because we compute anon shmem size using the longest vma size. To fix this we can use real anon shmem size that we can try to get using stat syscall on /proc/pid/map_files/%lx-%lx file.
