### ISSUE TITLE
KVM checkpointing progress

### ISSUE THREAD

**Issue by rc979** [checkpoint-restore/criu#229]
Pavel,
Has any progress been made in checkpointing KVM since we last spoke at Dockercon this year?
Thanks.

**Comment by xemul** [comment]
@rc979 , nope, we haven't played with this at all. C/R of VMs with CRIU is not what we actually planned to do, so this talk is not in top-prio in our todo list :)

**Comment by eabatalov** [comment]
@rc979  could you please describe the benefits of VMs C/R with CRIU comparing to standard VMs snapshotting functionality? VMs code should be already optimized for quick boot from saved snapshots.

**Comment by rc979** [comment]
@eabatalov Sorry for the delay here. Yes, you're right but it would be one less step before checkpointing. Also, you'd have to suspend or shutdown the VMs every time you want to checkpoint which might not be always feasible.

**Comment by hw-claudio** [comment]
> @rc979 could you please describe the benefits of VMs C/R with CRIU comparing to standard VMs snapshotting functionality? VMs code should be already optimized for quick boot from saved snapshots.

Also landed here, as VM code for save restore in QEMU/libvirt is currently very slow. Have there been attempts to use CRIU with QEMU before? Is this known not to work because of something fundamental?

Thanks

**Comment by rppt** [comment]
> Is this known not to work because of something fundamental?

For VMs that do not use SRIO-V this should be possible. For that CRIU should be able to save/restore the state of all special devices QEMU uses. In the simplest case this would be only `/dev/kvm`, but generally, there should be support for virtio, VFIO, and so on. I don't think there is a fundamental issue with those, but this is a lot of work to implement support for KVM etc and even more work to keep this support up to date.

And I'm not sure CRIU will perform better than QEMU anyway, because QEMU only saves and restores the VM state with some insight about what VM is doing, but CRIU will have to save and restore QEMU state pretty much as a black box.

**Comment by hw-claudio** [comment]
Thanks for your answer, there would be a lot of work to implement explicit support for KVM I understand, so probably better to try to put the work into QEMU instead to improve the save and restore performance.
