### ISSUE TITLE
Pre-dump hist the number of open files limit on huge mem tasks

### ISSUE THREAD

**Issue by pragyasardana** [checkpoint-restore/criu#239]
I am using criu v2.2 and when i give a predump command on linpack process I get an error: 
**Error (page-pipe.c:49): page-pipe: Can't make pipe for page-pipe: Too many open files**
I am attaching the screenshot of the logs
![screenshot from 2016-11-03 16-22-36](https://cloud.githubusercontent.com/assets/19503101/19983784/c984078a-a1e1-11e6-81d0-58f6760cbc72.png)

**Comment by xemul** [comment]
Did you run criu from root? Is it possible to get logs as text file? :)

**Comment by pragyasardana** [comment]
Thank you for your quick response. I am logged in as the root user. I am attaching a copy of the complete logs for the process. The process being used is Intel Linpack Benchmark ( https://software.intel.com/en-us/articles/intel-mkl-benchmarks-suite ).
[log.txt](https://github.com/xemul/criu/files/570313/log.txt)

**Comment by xemul** [comment]
OK. What does ulimit -a show?

**Comment by pragyasardana** [comment]
thank you for your response. I am attaching the output of the command

core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 29875
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 29875
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

**Comment by xemul** [comment]
Cool. So as a workaround (it's a bug, yes, and we plan to fix it) you can try increasing the number of open files with
# ulimit -n 65536

**Comment by xemul** [comment]
What's in /proc/sys/fd/nr_open file?

**Comment by pragyasardana** [comment]
the file contains "1048576"

**Comment by xemul** [comment]
OK. So... The problem is that the amount of memory to be dumped is ~4Gb. And existing CRIU implementation tries to get all this memory into a set of pipes. One pipe, according to your logs, can keep 200 pages, which is ~1Mb, thus we need 4k pipes to keep this, each pipe is 2 descriptors so we need 8k descriptors. In your logs the pipe() aborts at 400 pipes, which is 800 descriptors.

The global counter allows 1M descriptors, ulimit was set to 1k, but you tell you've raised the value. Are you sure you've done it in the same shell in which you run criu? Try setting this to unlimited.

    ulimit -n unlimited
