### ISSUE TITLE
Make it possible to show relative timestamps in criu logs

### ISSUE THREAD

**Issue by xemul** [checkpoint-restore/criu#341]
There are two places to fix.

1. `print_ts()` from `criu/log.c`
2. `sbuf_log_init()` from `compel/plugins/std/log.c`

Also callers of `std_log_set_fd()` and `parasite_init_daemon()` might need to correctly pass the starting timeval into parasite and restorer contexts.

**Comment by mitulkarnik** [comment]
I am interested to implement this enhancement. As per the suggestions given by Radostin on mailing list I am looking for possible solutions. 
Candidates:
clock_gettime() with CLOCK_MONOTONIC  parameter 
exploring more on similar lines

**Comment by mitulkarnik** [comment]
I am exploring the possibility of using clock_gettime with Clock_Id as CLOCK_MONOTONIC_RAW which eliminates the skews caused by ntp or adjtime. I want to know if this approach works on all platforms 
something like 

`clock_gettime(CLOCK_MONOTONIC_RAW, &timespec);`
I have created the patch for the same and am able to generate the relative timestamps as well. 
Have doubt if this approach works.  Will send out the patch soon

**Comment by xemul** [comment]
Actually, the idea behind this issue was quite simple -- when printing a new line in logs get the time of the previous line, subtract it from the current time and print the result. We all wanted to see in logs the amt of time each line takes to roughly estimate the "weight" of each operation.

**Comment by nishant-08** [comment]
Hello.
Is this enhancement still desirable? I found this interesting and would like to work on this. My idea is pretty similar to what xemul mentioned, i.e. subtracting previous time from current time.

**Comment by xemul** [comment]
Yes. Patches are welcome
