### ISSUE TITLE
[Docker] Erratic, chaotic behaviour

### ISSUE THREAD

**Issue by jvlatzko** [checkpoint-restore/criu#365]
Hi again, 

after #359 I've run into another problem. This time, I do not* get an error _per se_, but instead the container does not work as expected. 

**Description:** 
I use an iperf-server container and observe the behaviour of the c/r process while a docker-iperf-client is connected and testing: 

```
#!/bin/bash
docker network create iperf-net
docker run -d --net iperf-net -p 5201:5201 --name iperf-server moutten/iperf:3.1
docker run -d --net iperf-net --name iperf-client moutten/iperf:3.1 -c iperf-server -t 120 -b 1000000

for i in 1 2 3 4 5
do
        echo 'Waiting 5 s....'
        sleep 5
        docker checkpoint create --checkpoint-dir=/tmp iperf-server cp$i
        docker rm -f iperf-server
        docker create --net iperf-net -p 5201:5201 --name iperf-server moutten/iperf:3.1
        echo 'Resuming iperf...'
        docker start --checkpoint-dir=/tmp --checkpoint=cp$i iperf-server
        echo "Restore $i complete"
done

echo "Log of client: "
docker logs iperf-client
sleep 1

echo "Cleaning up..."
docker rm -f iperf-client
sleep 1
docker rm -f iperf-server
docker network rm iperf-net
sudo rm -rf /tmp/cp*
echo 'Finished!'
```

The client's [log](https://pastebin.com/evgHYkMH) shows the client exited with an error before the experiment ended, but without any errors reported by CRIU. Funnily enough, in this specific case the client container dies after the very first checkpoint. Note that while one might think this to be a race condition, the same behaviour occurs if the iperf-client is started with a UDP option so that TCP is not at fault. 

* / Caveat: 
Note that this behaviour is not deterministic. We have seen the script run all through the end with _no errors in the client's log_ whatsoever **and** correct behaviour of both containers :-/ On the other hand, `Error response from daemon: oci runtime error: criu failed: type NOTIFY errno 0 ` has _again_ occurred at times. In these cases, messages like `Error response from daemon: shim error: open /tmp/cp5/config.json: no such file or directory` were printed. 

Setup: 
Ubuntu, `uname -r
4.8.0-58-generic` docker Version 17.03.1-ce
CRIU compiled from source on july 11. 

If this report is too close to #359 and a link suffices, feel free to close either - I'm new to bugreporing via git. 
Thanks!

**Comment by xemul** [comment]
You seem to restore a container on a different file tree, than the one you did checkpoint on, don't you?

**Comment by jvlatzko** [comment]
Am I? Maybe I misunderstood, but I don't see that my approach qualifies as such. It is the same machine, the same directory the script is run, the same everything? 
Can you help me sort this out so that I understand it? :-)

**Comment by xemul** [comment]
Sure :) You do

docker create
docker checkpoint
docker rm
docker create
docker restore

After step 1 you have root of you container in some state (i.e. -- some files present with some contents). At step 2 criu saves state of the container and this state includes references on the filesystem from step 1 (i.e. -- names of opened and mapped files and cwd directories). At step 3 you remove the filesystem of the container and on step 4 recreate it from scratch.

Here's the most important part -- filesystem states after step 1 and right before step 2 differ. Because container have been running for a little bit after you created it and changed some files (removed or renamed them, created some new). So in the image we have references on files at state 2, while on step 4 you effectively roll-back it to the point at step 1.

Next you try to do the restore. During restore criu tries to open/mmap/cwd files/dirs by their names as criu saw them at step 2, but fs looks like step 1. No wonder, that restore _may_ fail.

You can proceed to issues #294 and #293 (the latter one contains discussion how do overcome this), this problem is very well known, and Docker guys are about to fix it :)
