### ISSUE TITLE
Consider treat pts fd in a tolerant way

### ISSUE THREAD

**Issue by zhouxinyu** [checkpoint-restore/criu#504]
Hi,

In some early docker versions, the pts fds are opened in the host os when entering the container with the command `docker exec -it $id bash`, so the fd 0/1/2 of the started process are pointed to the host mount namespace.

![image](https://user-images.githubusercontent.com/3961183/41049517-b1491efa-69e3-11e8-83ed-b6f86b36cf07.png)

So criu dump the reg file /dev/pts/12 will find the mnt_id is mismatch, so the dump may fail.

```
Error (criu/files-reg.c:1282): Can't lookup mount=152 for fd=1 path=/dev/pts/7
```
I wonder should we tolerate the mismatched mnt_id if the target fd is a pts?

**Comment by avagin** [comment]
In such cases, the master point of this pty is outside a container too. What behavior would you expect in this case?

**Comment by zhouxinyu** [comment]
Hi @avagin , thanks for your reply, is it a good solution that we don't compare the mnt_id if the dumped fd pointed to a pty?

**Comment by avagin** [comment]
@zhouxinyu First, each pty is slave and master points.  So pty can be dumped only if both its points belong to dumped processes, otherwise, it has to be dumped as external resources (https://criu.org/External_resources).

Second, if we will not compare the mnt_id, it isn't clear where we will create this pty on restore.

I think in your case a pty has to be dumped as an external resource. For example, you can look how it works in runc https://github.com/opencontainers/runc/commit/1c43d091a18a2f2dd73b46d49c678c265cf1ace3

**Comment by rst0git** [comment]
@zhouxinyu Another example for external resource dump/restore is the LXD/LXC implementation [lxc/criu.c](https://github.com/lxc/lxc/blob/master/src/lxc/criu.c#L222). I used the same idea to dump/restore pseudo terminals for [Libvirt-LXC containers](https://github.com/rst0git/libvirt/blob/lxc-migration/src/lxc/lxc_criu.c#L125L129).
