### ISSUE TITLE
Error transferring container data: When application benchmark is running in container

### ISSUE THREAD

**Issue by adityacloud1** [checkpoint-restore/criu#576]
Respected all,
Greeting of the Day !!!. I am trying to live migrate container ‘c1’ between 2 LXD servers, with apparmor security feature disabled and experimental setup is:

Physical machine OS: Ubuntu 16.04
lxc --version 3.7 (installed from source using: https://github.com/lxc/lxd)
lxd --version 3.7 (installed from source)
criu --version: 3.11 (installed from source)
kernel --version: 4.15.0-29-generic
To debug lxd, using lxd --debug and container **c1 is migrated successfully in idle state** (no workload running), but when workload benchmarks are running inside c1, it always results in _**Error transferring container data: migration dump failed**_
. 
1. Screenshot for error
![error](https://user-images.githubusercontent.com/40225508/48834196-23bf6c80-eda3-11e8-940e-e2992b968e58.png)
2. Screenshot for lxd --debug
![lxd](https://user-images.githubusercontent.com/40225508/48834205-2b7f1100-eda3-11e8-9b9f-b806dda27ba0.png)
3. lxc.log

[lxc.log.docx](https://github.com/checkpoint-restore/criu/files/2603754/lxc.log.docx)
4. migration_restore.docx
[migration restore.log.docx](https://github.com/checkpoint-restore/criu/files/2603759/migration.restore.log.docx)

Any help is greatly appreciated !!!.

**Comment by adrianreber** [comment]
The CRIU screenshot error looks like apparmor again and the second screenshot shows no error.

Please attach the log files directly without putting them into a .docx file.

The restore log looks successful. For me this seems like a collection of unrelated log files and screenshots. This is totally confusing and I have no idea what you are doing, and from where you have the log files. Why is the restore successful if the checkpoint fails. This makes no sense.

In other reports you wrote that the migration works.

**Comment by adityacloud1** [comment]
Respected sir,
Thanks for the response.
1. I am out of station for three days,, will attach the log files on Sunday.
2. Actually, my target is to migrate lxd container when benchmark workloads are running, but it results in migration dump failed.
3. However, lxd container is successfully migrated when no workloads is running i.e in idle state.

**Comment by adrianreber** [comment]
Okay, good to know. So migration works but not under load. If it is a CRIU problem the log files of the dump or restore would be most interesting.

**Comment by adityacloud1** [comment]
Yes sir, I will upload those log files on Sunday.
Now, I am out is station. My research setup not accessible.

**Comment by adityacloud1** [comment]
Respected sir,
Greetings of the day !!!
1. Container migration under load gives error:
`EROR[11-28|10:56:01] Rsync send failed: /var/lib/lxd/containers/c1/: exit status 24: file has vanished:`
Screenshot is:
![screenshot from 2018-11-28 10-54-38](https://user-images.githubusercontent.com/40225508/48994817-2a672e80-f16b-11e8-9527-9367b1f9eb00.png)
2. **dump log file** attached is here:
[migration_dump_2018-11-28T10:32:11+05:30.log](https://github.com/checkpoint-restore/criu/files/2614162/migration_dump_2018-11-28T10.32.11%2B05.30.log)

**Comment by adrianreber** [comment]
What is running in you container?

Please also attach the LXD log file.

From what I see I would say that during the initial rsync of the file system, before CRIU starts the process dumping, files are changing and therefore rsync fails. This is just a guess, as I would need the complete LXD log file. But if this is true, then it would need a different rsync handling in LXC to ignore/skip vanished files.

**Comment by rst0git** [comment]
I noticed the following error message in the dump log file:
```
(00.123638) Error (criu/sk-netlink.c:77): netlink: The socket has data to read
```
the comment of Tycho [here](https://github.com/lxc/lxd/issues/2522#issuecomment-254711481) was:
> this is a known issue; the workaround is simply to try again.

@adityacloud1 What happens if you try again?

**Comment by adrianreber** [comment]
The errors with the vanishing files could be difficult to fix. If you are compiling LXD yourself you could try to find the place where rsync is started and then add `--ignore-missing-args` which should ignore any errors due to missing file. As a final rsync will be done once the container is quiesced, it should not be a problem.

Maybe try a workload which does not change the filesystem that much to avoid this error.

Also, you could try to disable pre-copy migration to see how LXD container migration works without pre-copy.

Also, not sure if that works, maybe `lxc pause --stateful`, `lxc move`, `lxc unpause`. You have to look up the correct parameters, I just did a guess how `pause` works.

**Comment by adityacloud1** [comment]
Respected sir,
thanks for yours valuable suggestions. I tried the followings:
1. For the workloads like Apache web-server, lmbench, which does not change filesystem `Rsync send failed`**error does not occur.**

2. By **disable pre-copy migration**, LXD works with same  `Rsync send failed` error.

3. To add  `--ignore-missing-args` in rsync,  explored [https://github.com/lxc/lxd/blob/master/lxd/rsync.go](url), but yet not success. 

4. `lxc pause --stateful`may not fulfill my objective to test container migration during workloads running state.

Furthermore, please guide **_how to measure downtime_** during the container migration?

**Comment by adityacloud1** [comment]
Respected sir,
thanks for yours valuable suggestions. I tried the followings:
1. For the workloads like Apache web-server, lmbench, which does not change filesystem `Rsync send failed`**error does not occur.**

2. By **disable pre-copy migration**, LXD works with same  `Rsync send failed` error.

3. To add  `--ignore-missing-args` in rsync,  explored [https://github.com/lxc/lxd/blob/master/lxd/rsync.go](url), but yet not success. 

4. `lxc pause --stateful`may not fulfill my objective to test container migration during workloads running state.

Furthermore, please guide **_how to measure downtime_** during the container migration?

**Comment by adityacloud1** [comment]
Respected @adrianreber, any comment please for the downtime measurement.

**Comment by adrianreber** [comment]
Measuring container downtime during migration is really hard.The problem is that neither CRIU nor LXC/LXD give you an exact timestamp when the container is stopped. Even if you have such a flag (it would be easy to add to CRIU's stats-dump) it does not really help as the clocks of the involved system would need to be synced. So it depends how good you can sync the clocks of the involved systems.

My approach for the FOSDEM 2018 demo was a process which slept 100µs and than it compared the time before and after the sleep. Reading the clock twice and sleeping 100µs took about 400µs. If those steps required more than 400µs I guessed something happened (maybe a migration) and I counted the lost sleeps. So this was not very accurate, but if only migrating in one direction I could get a feeling for the time required to migrate.

To accurately measure the migration downtime it really difficult. So you have to find a way which gives you results which are good enough for you.

**Comment by adityacloud1** [comment]
Respected sir,
Thanks for yours reply
