### ISSUE TITLE
checkpoint android ashmem memory space

### ISSUE THREAD

**Issue by xiechao4** [checkpoint-restore/criu#582]
hi
i am trying to checkpoint-restore a android process, but it failed to checkpoint ashmem space.
it reports errors at 
criu/proc_parse.c         if (is_anon_shmem_map(st_buf->st_dev)) {
                                          if (!(vma_area->e->flags & MAP_SHARED))
                                              goto err_bogus_mapping;
the vma is
12c00000-1322e000 rw-p 00000000 00:05 32427                              /dev/ashmem/dalvik-main space (deleted)
how can i handle ashmem checkpoint/restore?

**Comment by rppt** [comment]
CRIU lacks support ashmem mappings.

There was a discussion about it a while ago (https://lists.openvz.org/pipermail/criu/2016-March/026892.html, https://lists.openvz.org/pipermail/criu/2016-April/027138.html), and since then nothing really changed :(

AFAIK, nobody works on adding ashmem support to CRIU, so you are welcome to add it :-)

**Comment by x1022as** [comment]
Hi,  @xiechao4  @rppt  @xemul  what's the status here? And if no trouble, can anyone tell me how is criu capable of checkpointing/restoring android applications :)

I am really interested in this, but still working on environment for now :man_facepalming:

**Comment by 0x7f454c46** [comment]
Let's keep it open: the root-cause in known, it's about Android's ashmem support.
