### ISSUE TITLE
[Question] tty + docker + kubernetes

### ISSUE THREAD

**Issue by marekzmyslowski** [checkpoint-restore/criu#586]
I'm trying to restore the image inside docker on the kubernetes. I'm almost there except this:
`98: Error (criu/tty.c:1016): tty: Don't have tty to inherit session from, aborting
    98: Error (criu/files.c:1203): Unable to open fd=0 id=0x4
`
Anyone know how to fix this?

Regards
Marek

**Comment by rst0git** [comment]
@marekzmyslowski I think you need to pass `-j` (`--shell-job`) on restore.

**Comment by rst0git** [comment]
Just to mention. If you get errors of the type:
```
Error (criu/files-reg.c:1713): File usr/bin/bash has bad size 1199896 (expect 866600)
```
This is because some files in the container's root file system are not the same (i.e. have different size) from the ones in the environment where the checkpoint was created.

Assuming that you are creating a checkpoint of a process on the host and restoring inside a container, the proper solution would be to make sure that both environments (i.e. the host and the container) have the same packages installed. Of course, a quick fix would be to use a bind mount (e.g. `-v /usr:/usr:ro`)

**Comment by xemul** [comment]
@marekzmyslowski , can you drop me an email? I'd like to introduce you to another guy interested in k8s pods migration and asking me if there's anybody else playing with it :)

**Comment by marekzmyslowski** [comment]
@xemul  - It is marekzmyslowski@poczta.onet.pl
@rst0git - with "-it" it works but the trick is not to use it. Kuberenetes doesn't run the dockers with interactive console.

**Comment by rst0git** [comment]
> with "-it" it works but the trick is not to use it. Kuberenetes doesn't run the dockers with interactive console.

In such case, would it be possible to deattach the process from the tty upon start?
Similar to the _simple loop_ example:
```
$ setsid ./test.sh  < /dev/null &> test.log &
```

**Comment by marekzmyslowski** [comment]
@rst0git  Thanks for the hint. It worked. I was able to run the code under the Kuberenetes.
Thank you for the help and all the best in New Year :)
