### ISSUE TITLE
migrating container running openvswitch fails 

### ISSUE THREAD

**Issue by phenix317** [checkpoint-restore/criu#659]
Hello,

It seems that we have found another problem during the dump part of the live migration, dump failed and the error showed in the log is:

Error (criu/net.c:461): Unsupported link 2 (type 1 kind openvswitch)

Basically, we are trying to run an OVS inside an LXC and migrate it, but this seems to fail.

The Hosting Machine information:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
kernel version: 4.4.0-62-generic (i tried with 4.13 same error)

############################################################################CRIU: Version: 2.6

############################################################################
LXC:

2.0.9

The dump log:
[dump.log](https://github.com/checkpoint-restore/criu/files/3022070/dump.log)

BR,

**Comment by xemul** [comment]
That's because of unknown to CRIU network device of kind "openvswitch". Each netdev should be handled carefully, so when meeting an unknown one CRIU fails. We currently support lo, bridges, tun/tap-s and some tunnels (e.g. sit).

Adding a new netdev is not an extremely complex task, but we don't have anyone who's involved in ovs _that_ much :) If you could contribute the code, that'd be awesome. From our side we can fully guide you through the CRIU's netdev dump/restore architecture.

**Comment by phenix317** [comment]
Hi xemul,

I was navigating through the source code while waiting answers, yes what you are saying is true. I guess, it should not be quite different from bridges ?

If I can get commits for adding bridges support it will help for the addition of the OvS support.

BR,

**Comment by rst0git** [comment]
https://github.com/lxc/lxc/issues/2909

**Comment by Snorch** [comment]
Note: support of openvswitch is implemented in Virtuozzo criu https://src.openvz.org/projects/OVZ/repos/criu/commits/bd5b3d908 + vzkenel https://src.openvz.org/projects/OVZ/repos/vzkernel/commits/38719b34f83

One can try porting it.
