### ISSUE TITLE
Remote option in C API or RPC

### ISSUE THREAD

**Issue by arvchristos** [checkpoint-restore/criu#731]
Hello! 
I would like to ask if there is any way to achieve remote process restore using the C API, as stated [here](https://criu.org/CLI/opt/--remote). If negative, is there a way to achieve the same thing using the  #RPC?

**Comment by adrianreber** [comment]
> I would like to ask if there is any way to achieve remote process restore using the C API, as stated [here](https://criu.org/CLI/opt/--remote).

No, the whole `--remote` support (which includes image proxy) is not wired up in the C API.

> If negative, is there a way to achieve the same thing using the #RPC?

No, as far as I can tell (from a quick look at the code), it is not yet possible.

But if you are interested in it we are always happy to accept patches.

Your question is actually pretty good, because the `R` in RPC stands for remote, but in CRIU's case it does not really mean from another host. The RPC/C API architecture is that existing functionality (in this case `--remote`) needs to be made available in `criu/cr-service.c`. To use it via RPC it needs to be added to the RPC protobuf definitions. Now it should be possible to use it via RPC. The C API is just a wrapper around the protobuf definition and removes the necessity to set up the communication to the CRIU process via RPC manually.

The whole RPC communication uses file descriptors, so that RPC could really be used from remote by sending the RPC commands over the network.

So in theory everything you ask for is possible. Using RPC from a remote host and using CRIU's `--remote` functionality through RPC. But everything still needs to be connected to the right endpoints. Probably not the answer you were looking for.

@rst0git is heavily involved with the `--remote` support. Did I describe it correctly?

**Comment by arvchristos** [comment]
@adrianreber Thank you for the immediate response. Seeking for relevant info in the mailing list, I found @rst0git patches (February 2018) about this feature and I wonder what is left to be addressed before including it in dev branch.

**Comment by rst0git** [comment]
Hi @arvchristos 

> I wonder what is left to be addressed before including it in dev branch.

Adding the `--remote` option (and image-cache/proxy) to RPC and `libcriu` is not difficult (and this [patch](https://lists.openvz.org/pipermail/criu/2018-February/040421.html) series does that) but the current implementation is not very efficient and not well tested (e.g. it does not work well with pre-dump and lazy-pages).

I have been working on addressing the following issues and I am hoping to discuss this topic at LPC later this year:

- pre-dump support: The current implementation of the `--remote` option is using the concept of "snapshot" (or namespace) which is similar to how CRIU `dump` and `pre-dump` work - the combination of file name and image directory path is used as a unique identifier for every image. The main idea is that if we use `pre-dump` (without the `--remote` option) we have to specify a different `--images-dir` in every iteration of a pre-copy migration, and with `--prev-images-dir` we specify the path to a directory where the previous `pre-dump` checkpoint was stored. However, in the context of live migration when using the `--remote` this becomes unnecessary because during `pre-dump` CRIU checkpoints only memory pages of a target process tree. Thus, we don't need to keep an older version of modified memory pages stored on the destination side and such cached memory should be free-ed or overwritten.

- post-copy support: As Rodrigo explained in [this email](https://lists.openvz.org/pipermail/criu/2015-September/022029.html), the `--remote` option was not intended to be used with `page-server` and because these two features implement a similar functionality Pavel [responded](https://lists.openvz.org/pipermail/criu/2015-September/022038.html) with:

> OK, so as I told above -- I'm OK to deprecate the page-server with newer image proxy and cache.

Nowadays, the page-server has been integrated into several upstream projects (e.g. lxc, runc, etc.) and it provides support for post-copy migration.

Since the `--remote` option is only available in the dev branch, we can refactor its implementation to support pre-, post- and hybrid-copy migration without breaking backwards compatibility and reusing as much code as possible from the page-server component.

- TLS support: Currently, the `--ps-socket` option allows to pass an open file descriptor which can be used for remote communication. This is intended to be used in case when an external application already has a communication channel. However, to provide security, such application needs to act as a proxy that reads/writes from the provided file descriptor and encrypts/decrypts data that is being sent over the network. More efficient approach for secure communication is to avoid this unnecessary proxy layer.

- UNIX sockets: Speaking of unnecessary proxy layer, the use of UNIX sockets for image-cache and image-proxy introduces a performance overhead that can be avoided with direct client-server communication. For example:
```sh
[dst] $ criu restore --remote --port $PORT ...
[src] $ criu pre-dump --remote --port $PORT --address $ADDR ...
[src] $ criu pre-dump --remote --port $PORT --address $ADDR ...
...
[src] $ criu dump --remote --port $PORT --address $ADDR ...
```
where the `restore` action integrates the image-cache component and acts as a server (listening on port `$PORT`); `dump`/`pre-dump` acts as a client (i.e. sends the data that would otherwise be stored in image files). In practice, it is better to keep a single TCP connection open rather than reconnecting multiple times and this is where the `--ps-socket` option might be useful.

- integration with container runtimes: Almost every container runtime that aims to implement support for live migration starts by adding support for checkpoint and restore. In order to achieve this it is necessary to somehow interact with CRIU (e.g. lxc is using command-line API, runc is using go-criu, etc.). The idea of the [P.Haul](https://criu.org/P.Haul) project was to provide a library that implements a live migration algorithm based on CRIU. However, implementing checkpoint and restore support is usually not a very simple task, takes some time, and once complete, it is easier to extend this initial implementation to enable pre-copy (`pre-dump`) and post-copy (`lazy-pages`) rather than introducing yet another dependency (P.Haul). IMHO the purpose of the `--remote` option is similar to what P.Haul was intended to provide but as a feature which is part of CRIU rather than an external library.

Of course, all of the above is just what I think about the `--remote` option and I hope to discuss this topic in more detail at LPC in September.
