### ISSUE TITLE
ERRORS when checkpoint 

### ISSUE THREAD

**Issue by suang207** [checkpoint-restore/criu#769]
When I tried to dump a process using CRIU, the following error occurred. I don't know what happened.

root@My-PC:/home/suang/Experiments/criu-3.12/criu# ./criu dump --shell-job --images-dir /home/suang/Experiments/ckp1 -t 8092 --ghost-limit 100M
Warn  (criu/image.c:134): Failed to open parent directory
Warn  (compel/arch/x86/src/lib/infect.c:280): Will restore 8092 with interrupted system call
Error (criu/cr-dump.c:1349): Dump eventpoll (pid: 8092) failed with -1
Error (criu/cr-dump.c:1742): Dumping FAILED.

**Comment by rst0git** [comment]
Would it be possible to provide a debug log (i.e. using `-v4` flag)?
```
./criu dump -v4 -o dump.log --shell-job --images-dir /home/suang/Experiments/ckp1 -t 8092 --ghost-limit 100M
```

**Comment by WeiAt931** [comment]
Thank you very much for your reply.
I found the reason for the mistake, albeit somewhat incredible. This error is because I started my program in the terminal of visual studio code. If I start my program directly in the system terminal, the error disappears.
Below is a section of the error log. (dump. log is too long) I think it will help CRIU get better.

(00.029242) ----------------------------------------
(00.029258) epoll: kid_lookup_epoll: no match pid 15786 efd 21 tfd 3 toff 0
(00.029267) Error (criu/cr-dump.c:1349): Dump eventpoll (pid: 15786) failed with -1
(00.029292) Waiting for 15786 to trap
(00.029325) Daemon 15786 exited trapping
(00.029354) Sent msg to daemon 3 0 0
(00.029377) Force no-breakpoints restore
(00.029405) 15786 was trapped
(00.029408) 15786 (native) is going to execute the syscall 45, required is 15
(00.029438) 15786 was trapped
(00.029441) `- Expecting exit
(00.029469) 15786 was trapped
(00.029472) 15786 (native) is going to execute the syscall 186, required is 15
(00.029478) 15786 was trapped
(00.029481) `- Expecting exit
(00.029488) 15786 was trapped
(00.029491) 15786 (native) is going to execute the syscall 1, required is 15
pie: 15786: __fetched msg: 3 0 0
(00.029505) 15786 was trapped
(00.029507) `- Expecting exit
(00.029519) 15786 was trapped
(00.029522) 15786 (native) is going to execute the syscall 186, required is 15
(00.029528) 15786 was trapped
(00.029530) `- Expecting exit
(00.029537) 15786 was trapped
(00.029540) 15786 (native) is going to execute the syscall 186, required is 15
(00.029546) 15786 was trapped
(00.029549) `- Expecting exit
(00.029556) 15786 was trapped
(00.029559) 15786 (native) is going to execute the syscall 1, required is 15
pie: 15786: 15786: new_sp=0x7f9e0e11e008 ip 0x7f9e0d66c9a4
(00.029567) 15786 was trapped
(00.029570) `- Expecting exit
(00.029576) 15786 was trapped
(00.029579) 15786 (native) is going to execute the syscall 3, required is 15
(00.029591) 15786 was trapped
(00.029593) `- Expecting exit
(00.029600) 15786 was trapped
(00.029602) 15786 (native) is going to execute the syscall 3, required is 15
(00.029608) 15786 was trapped
(00.029611) `- Expecting exit
(00.029617) 15786 was trapped
(00.029620) 15786 (native) is going to execute the syscall 15, required is 15
(00.029628) 15786 was stopped
(00.029725) Unlock network
(00.029730) Unfreezing tasks into 1
(00.029733) 	Unseizing 15786 into 1
(00.029739) Error (criu/cr-dump.c:1742): Dumping FAILED.
