### ISSUE TITLE
Include tests for validating Java APIs work fine with CRIU

### ISSUE THREAD

**Issue by nidhi1605** [checkpoint-restore/criu#820]
The goal of this issue is to include tests to verify if Java Applications work with CRIU. We plan to introduce Java based CRIU APIs so that a Java App can do self checkpoint and restore.

We have included Java functional tests that uses the Java File based APIs, Memory mapping APIs and Socket based APIs and places the process in various states before check pointing and validates if these resources are still accessible after restore. It also validates if the file contents or socket connections are in the expected state.

The file based tests are here in our local repo - https://github.com/nidhi1605/criu/tree/javaTests/test/javaTests
Let us know if the format of the tests are fine, we will create a PR here.

**Comment by adrianreber** [comment]
> We plan to introduce Java based CRIU APIs so that a Java App can do self checkpoint and restore.

Where do you plan to introduce those APIs?

If you could share some additional information it would make it a lot easier to understand what this is exactly about. I had a look at the branch and there are a lot of commits and it is hard to tell what this is really about.

Right now it seems you want to include a Java wrapper, maybe it could be called library, into the test directory. One of my main questions is, where should the Java <-> CRIU interface live which you want to test. If it is a library it might leave under lib/, but I know there is an external Ruby lib and recently will also moved the go-bindings out of the main tree.

I also see that the test uses maven, from my last encounter with maven I remember it takes forever. So I am a bit worried about our test runtime if this is included.

My main questions right now are, where should the Java binding live? If we know that location it makes sense to talk about tests. At least for me. Some background about your use case would also be helpful.

**Comment by dinogun** [comment]
Hi @adrianreber, Thank you for your prompt response, Really appreciate it ! 

The question that we have is about adding Java application tests for the existing CRIU Interface to begin with. The goal is to augment the existing tests by adding Java application tests that test CRIU. I think this can be optional tests so that they have to be specifically invoked for them to run. That way they do not add additional overhead for your everyday testing.

The main aim is to help the Java ecosystem to get more confidence in CRIU and to demonstrate that regular Java applications work well with CRIU. (and hopefully iron out any issues that we find along the way). This would be the first step.

The next step would be to introduce Java API's for doing checkpoint-restart, so that Java applications can self checkpoint. We are still a long way from this and there have been some design discussions at IBM and others and I think needs a broader participation from the Java community to help arrive at the right design.

So this issue is only to address if you would be interested to add additional Java based tests that augment the existing ones. They can exist in `criu/test/java` and maybe not call it as part of the default target so as to not add any testing overhead to begin with.

**Comment by adrianreber** [comment]
Including an additional test suite should be no problem. We have seen, however,  that test suites which are not regularly run tend to not work after some time, but that would be up to you to make sure it keeps working.

So I would recommend to submit a pull request for your tests. No promises it will be merged, though. But seeing the actual tests you want to merge would make it easier to discuss about it.

**Comment by rst0git** [comment]
@nidhi1605 @dinogun I don't know how relevant this would be to your work but there was one interesting publication that might be worth considering:
 [Initialize Once, Start Fast: Application Initialization at Build Time](https://github.com/checkpoint-restore/criu/files/3726717/Initialize_Once_Start_Fast_Application_Initialization_at_Build_Time.pdf)
> We believe that our approach is more suitable for microservices than checkpoint/restore systems,e.g., CRIU [CRIU 2019], that restore a Java VM such as the Java HotSpot VM...

**Comment by nidhi1605** [comment]
Thank you so much for your inputs. We will be opening a PR shortly.

**Comment by adrianreber** [comment]
Closing. See #825
