### ISSUE TITLE
Container is not destroyed with pre-dump

### ISSUE THREAD

**Issue by levanthanh3005** [checkpoint-restore/criu#982]
Hi,
Could you please help me to check the error with runc:
My steps are:
mkdir /mycontainer
cd /mycontainer
mkdir rootfs
docker export $(docker create busybox) | tar -C rootfs -xvf -

runc spec

Then change config.json : as the example in github https://github.com/opencontainers/runc
		"terminal": false,
		"user": {
			"uid": 0,
			"gid": 0
		},
		"args": [
			"sleep", "50000"
		],

Then go to mycontainer
runc run -d busybox &> /dev/null < /dev/null 
runc checkpoint --image-path cp busybox => it works

I reproduce the steps to make the busybox run again, and then run
runc checkpoint --pre-dump --image-path cp busybox
=> ERRO[0000] container is not destroyed                   

criu version is 3.13
runc version 1.0.0-rc9+dev
commit: c4d8e1688c816a8cef632a3b44a38611511b7140
spec: 1.0.1-dev

**Comment by adrianreber** [comment]
The error message `ERRO[0000] container is not destroyed` is probably wrong.

That the container keeps running is the correct behaviour if you use `--pre-dump` because it requires a final dump referencing the pre-dump. Are you complaining about the message or about the behaviour that the container keeps on running?

In any case, this would make sense to report at runc and you can tag me in the report. I can have a look at it there.

**Comment by levanthanh3005** [comment]
Hi,
I also report in runc in
https://github.com/opencontainers/runc/issues/2253
Could you please take a look,
Thank you

**Comment by levanthanh3005** [comment]
I close this issue since it is duplicated in
https://github.com/opencontainers/runc/issues/2253
